### ISSUE TITLE
Ghostscript error when executing `test copyobj`

### ISSUE THREAD

**Issue by mmuetzel** [octave-snap/octave-snap#86] opened 2021-05-14 18:46 UTC
`test copyobj` fails with the following error:
```
>> test copyobj
GPL Ghostscript 9.26: Can't find initialization file gs_init.ps.
***** testif HAVE_MAGICK; any (strcmp ("gnuplot", available_graphics_toolkits ()))
 toolkit = graphics_toolkit ();
 graphics_toolkit ("gnuplot");
 unwind_protect
   h1 = figure ("visible", "off", "paperposition", [0.25, 2.5, 8.0, 6.0]);
   x = 0:0.1:2*pi;
   y1 = sin (x);
   y2 = exp (x - 1);
   ax = plotyy (x,y1, x-1,y2, @plot, @semilogy);
   xlabel ("X");
   ylabel (ax(1), "Axis 1");
   ylabel (ax(2), "Axis 2");
   axes (ax(1));
   text (0.5, 0.5, "Left Axis", ...
         "color", [0 0 1], "horizontalalignment", "center");
   axes (ax(2));
   text (4.5, 80, "Right Axis", ...
         "color", [0 0.5 0], "horizontalalignment", "center");
   s1 = hdl2struct (h1);
   h2 = struct2hdl (s1);
   s2 = hdl2struct (h2);
   png1 = [tempname() ".png"];
   png2 = [tempname() ".png"];
   unwind_protect
     print (h1, png1);
     [img1, map1, alpha1] = imread (png1);
     print (h2, png2);
     [img2, map2, alpha2] = imread (png2);
   unwind_protect_cleanup
     unlink (png1);
     unlink (png2);
   end_unwind_protect
   assert (img1, img2);
   assert (map1, map2);
   assert (alpha1, alpha2);
 unwind_protect_cleanup
   close (h1);
   close (h2);
   graphics_toolkit (toolkit);
 end_unwind_protect
!!!!! test failed
unlink: operation failed: No such file or directory
>>
```

**Comment by mtmiller** [comment] 2021-05-14 19:01
Thanks, confirmed. Looks like we just need to add `GS_LIB` to the environment to point to the relocated ghostscript library directories.

**Comment by mtmiller** [comment] 2021-05-14 20:56
Fixed, will be part of the next nightly build. Thanks again for catching this oversight!

**Closed as completed** 2021-05-14 20:55 UTC
Labels: bug
